### ISSUE TITLE
capacitor v4 support ?

### ISSUE THREAD

**Issue by productdevbook** [Cap-go/capacitor-purchases#9]

**Comment by riderx** [comment]
Hello did you tried it in v4 ?
i still have to do that

**Comment by productdevbook** [comment]
yes, errors

**Comment by productdevbook** [comment]
```
E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: com.productdevbook.test, PID: 5411
    java.lang.IllegalArgumentException: com.productdevbook.test: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:174)
        at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:108)
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:86)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:75)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
E/uctdevbook.tes: Invalid ID 0x00000000.
```

**Comment by riderx** [comment]
@productdevbook can you provide a reproduction repo ? i did update capgo with v4 and i don't get your issue

**Comment by riderx** [comment]
I did test and that work on my side on v4

**Comment by productdevbook** [comment]
yes thats true my working
